// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using IngresoSwatch.ModelApi;
//
//    var rolloModel = RolloModel.FromJson(jsonString);

namespace IngresoSwatch.ModelApi
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class RolloModel
    {
        [JsonProperty("idrollo")]
        public long Idrollo { get; set; }

        [JsonProperty("rolloName")]
        public string RolloName { get; set; }

        [JsonProperty("sec")]
        public long Sec { get; set; }

        [JsonProperty("estado")]
        public string Estado { get; set; }

        [JsonProperty("idcontenedor")]
        public long Idcontenedor { get; set; }

        [JsonProperty("proceso")]
        public string Proceso { get; set; }

        [JsonProperty("idtpc")]
        public long Idtpc { get; set; }

        [JsonProperty("ancho")]
        public double Ancho { get; set; }
    }

    public partial class RolloModel
    {
        public static List<RolloModel> FromJson(string json) => JsonConvert.DeserializeObject<List<RolloModel>>(json, IngresoSwatch.ModelApi.ConverterRollo.Settings);
    }

    public static class SerializeRollo
    {
        public static string ToJson(this List<RolloModel> self) => JsonConvert.SerializeObject(self, IngresoSwatch.ModelApi.ConverterRollo.Settings);
    }

    internal static class ConverterRollo
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
